version: '2'

networks:
  mired:
    ipam:
      config:
        - subnet: 182.28.0.0/16
          gateway: 182.28.0.1

services:
  database:
    image: mysql:latest
    container_name: mysql_DB
    networks:
      mired:
        - ipv4_address: 182.28.0.11
    ports:
      - "3306:3306"
    expose:
      - 3306

  app-agenda:
    image: igr1985/agenda
    container_name: agenda
    networks:
      mired:
        - ipv4_address: 182.28.0.12
    expose:
      - 8081
    ports:
      - "8081:8081"
    depends_on:
      - database

